// Columnas de products que usa la app. Se piden por nombre en vez de "*"
// porque la tabla tiene la columna "embedding" (1536 números por producto,
// ~17 KB cada uno) que solo usa el asistente IA del lado del servidor: con
// "*" el catálogo bajaba ~36 MB por visita y el panel admin otro tanto.
export const PRODUCT_COLUMNS = [
  'id',
  'name',
  'slug',
  'short_description',
  'long_description',
  'price',
  'sale_price',
  'category',
  'categories',
  'garment_type',
  'sizes',
  'formats',
  'recommended_fabrics',
  'codigo',
  'precio_carton',
  'precio_pdf_a4',
  'precio_pdf_ploter',
  'disponible_carton',
  'disponible_pdf_a4',
  'mostrar_consulta_otro_formato',
  'precio_usd_carton',
  'precio_usd_pdf_a4',
  'precio_usd_pdf_ploter',
  'precio_usd',
  'precio_dxf',
  'precio_pds',
  'precio_mrk',
  'precio_ads',
  'precio_usd_dxf',
  'precio_usd_pds',
  'precio_usd_mrk',
  'precio_usd_ads',
  'free_until',
  'season',
  'entrega_inmediata',
  'main_image_url',
  'gallery',
  'is_active',
  'is_featured',
  'created_at',
  'view_count',
  'view_count_account',
  'view_count_no_account',
  'embedding_updated_at',
].join(',');
